accMockup/routes/web.php
<?php

use App\Http\Controllers\FrontendController;
use App\Http\Controllers\JournalController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/welcome', function () {
    return view('welcome');
});

Route::get('/', [FrontendController::class, 'dashboard'])->name('dashboard');
Route::get('/chartOfAccounts', [FrontendController::class, 'chartOfAccounts'])->name('chartOfAccounts');
Route::get('/newInvoice', [FrontendController::class, 'newInvoice'])->name('newInvoice');
Route::get('/newBill', [FrontendController::class, 'newBill'])->name('newBill');
Route::get('/balanceSheet', [FrontendController::class, 'balanceSheet'])->name('balanceSheet');
Route::get('/settings', [FrontendController::class, 'settings'])->name('settings');

Route::resource('journals', JournalController::class);

accMockup/app/Models/Journal.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Journal extends Model
{
    use HasFactory;

    protected $fillable = ['journalNo', 'reference', 'acc_date'];
}

accMockup/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

accMockup/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

accMockup/app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class FrontendController extends Controller
{
    public function dashboard()
    {
        return view('frontend.dashboard');
    }

    public function newInvoice()
    {
        return view('frontend.newInvoice');
    }

    public function newBill()
    {
        return view('frontend.newBill');
    }

    public function miscellaneousEntry()
    {
        return view('frontend.miscellaneousEntry');
    }

    public function chartOfAccounts()
    {
        return view('frontend.chartOfAccounts');
    }

    public function balanceSheet()
    {
        return view('frontend.balanceSheet');
    }

    public function settings()
    {
        return view('frontend.settings');
    }

    public function journalEntries()
    {
        return view('frontend.journalEntries');
    }
}

accMockup/app/Http/Controllers/JournalController.php
<?php

namespace App\Http\Controllers;

use App\Models\Journal;
use App\Http\Requests\StoreJournalRequest;
use App\Http\Requests\UpdateJournalRequest;
use Illuminate\Database\QueryException;

class JournalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $journals = Journal::orderBy('id', 'desc')->get();
        return view('frontend.journals.journalEntries', compact('journals'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('frontend.journals.miscellaneousEntry');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreJournalRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreJournalRequest $request)
    {
        try
        {
            Journal::create([
                'journalNo' => $request->journalNo,
                'reference' => $request->reference,
                'acc_date' => $request->acc_date
            ]);

            return redirect()->route('journals.index')->withMessage('Journal Saved!');
        
        }
        catch(QueryException $e)
        {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

        
    

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Journal  $journal
     * @return \Illuminate\Http\Response
     */
    public function show(Journal $journal)
    {
        return view('frontend.journals.journalDetails', compact('journal'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Journal  $journal
     * @return \Illuminate\Http\Response
     */
    public function edit(Journal $journal)
    {
        return view('frontend.journals.journalEdit', compact('journal'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateJournalRequest  $request
     * @param  \App\Models\Journal  $journal
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateJournalRequest $request, Journal $journal)
    {
        try
        {
            $journal->update([$request->all()]);
            return redirect()->route('journals.index')->withMessage('Journal Updated');
        }
        catch(QueryException $e)
        {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Journal  $journal
     * @return \Illuminate\Http\Response
     */
    public function destroy(Journal $journal)
    {
        $journal->delete();
        return redirect()->route('journals.index')->withMessage('Journal Deleted');
    }
}

accMockup/resources/views/frontend/balanceSheet.blade.php
<x-frontend.layouts.master>
    <h2>Balance Sheet</h2>
    <div style="display: flex; justify-content:space-around;">
        <h3><button type="button" class="btn btn-secondary">PDF</button></h3>
        <h3><button type="button" class="btn btn-secondary">XLSX</button></h3>
        <h3><button type="button" class="btn btn-secondary">SAVE</button></h3>
    </div>
    <table class="table">
        <thead>
            <th scope="col">ASSETS</th>
            <th></th>
        </thead>
        <tbody>
            <tr>
                <td>Current Assets</td>
                <td></td>
            </tr>
            <tr>
                <td>Bank and Cash Accounts</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Receivables</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Current Assets</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Prepayments</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Total Current Assets</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Plus Fixed Assets</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Plus Non-Current Assets</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Total ASSETS</td>
                <td></td>
            </tr>
        </tbody>
    

        <tr><td></td><td></td></tr>
        <tr><td></td><td></td></tr>
        <tr><td></td><td></td></tr>
        <tr><td></td><td></td></tr>
    
        <thead>
            <tr>
                <th scope="col">LIABILITIES</td>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Current Liablities</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Payables</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Total Current Liablities</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Plus Non-Current Liabilities</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Total LIABILITIES</td>
                <td>$0.00</td>
            </tr>
        </tbody>
    

        <tr><td></td><td></td></tr>
        <tr><td></td><td></td></tr>
        <tr><td></td><td></td></tr>
        <tr><td></td><td></td></tr>

    
        <thead>
            <tr>
                <th scope="col">EQUITY</td>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Current Year Unallocated Earnings</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Previous Years Unallocated Earnings</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Total Unallocated Earnings</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Retained Earnings</td>
                <td>$0.00</td>
            </tr>
            <tr>
                <td>Total EQUITY</td>
                <td>$0.00</td>
            </tr>
        </tbody>
    
        <tr><td></td><td></td></tr>
        <tr><td></td><td></td></tr>
        <tr><td></td><td></td></tr>
        <tr></tr>

    
        <thead>
            <th scope="col">LIABILITIES + EQUITY</th>
            <th scope="col">$0.00</th>
        </thead>
    </table>
</x-frontend.layouts.master>

accMockup/resources/views/frontend/chartOfAccounts.blade.php
<x-frontend.layouts.master>
    <h2>Chart Of Accounts</h2>
    <div class="container">
    <button type="button" class="btn btn-secondary">Create</button>
    <button type="button" class="btn btn-secondary">Export</button>
    </div>
    <table class="table">
        <thead>
            <th scope="col">Code</th>
            <th scope="col">Account Name</th>
            <th scope="col">Type</th>
            <th scope="col">Allow Reconciliation</th>
            <th scope="col">Account Currency</th>
            <th scope="col">
                <select>
                    <option>Group</option>
                    <option>Default Taxes</option>
                    <option>Tags</option>
                    <option>Allowed Journals</option>
                </select>
            </th>
        </thead>
        <tbody>
            <tr>
                <td>100000</td>
                <td>Asset</td>
                <td>??</td>
                <td>??</td>
                <td>
                    <select>
                        <option>BDT</option>
                        <option>USD</option>
                    </select>
                </td>
                <td><button type="button" class="btn btn-secondary">SETUP</button></td>
            </tr>

            <tr>
                <td>200000</td>
                <td>Liabilities</td>
                <td>??</td>
                <td>??</td>
                <td>
                    <select>
                        <option>BDT</option>
                        <option>USD</option>
                    </select>
                </td>
                <td><button type="button" class="btn btn-secondary">SETUP</button></td>
            </tr>

            <tr>
                <td>300000</td>
                <td>Equity</td>
                <td>??</td>
                <td>??</td>
                <td>
                    <select>
                        <option>BDT</option>
                        <option>USD</option>
                    </select>
                </td>
                <td><button type="button" class="btn btn-secondary">SETUP</button></td>
            </tr>

            <tr>
                <td>400000</td>
                <td>Income</td>
                <td>??</td>
                <td>??</td>
                <td>
                    <select>
                        <option>BDT</option>
                        <option>USD</option>
                    </select>
                </td>
                <td><button type="button" class="btn btn-secondary">SETUP</button></td>
            </tr>

            <tr>
                <td>300000</td>
                <td>Expense</td>
                <td>??</td>
                <td>??</td>
                <td>
                    <select>
                        <option>BDT</option>
                        <option>USD</option>
                    </select>
                </td>
                <td><button type="button" class="btn btn-secondary">SETUP</button></td>
            </tr>
        </tbody>
    </table>
</x-frontend.layouts.master>

accMockup/resources/views/frontend/dashboard.blade.php
<x-frontend.layouts.master>
    <h2>Accounting Dashboard</h2>
    <div class="container">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                <div class="card">
                    <img src="{{ asset('imgs/graphs.jpg') }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Customer Invoices</h5>
                        <p class="card-text">Invoices to Validate : 9</p>
                        <a href="{{ route('newInvoice') }}">
                            <button type="button" class="btn btn-secondary">New Invoice</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="{{ asset('imgs/graphs.jpg') }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Vendor Bills</h5>
                        <p class="card-text">Late Bills : 10 | Bills to Pay : 7</p>
                        <a href="{{ route('newBill') }}">
                            <button type="button" class="btn btn-secondary">New Bill</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="{{ asset('imgs/graphs.jpg') }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Miscellaneous Operations</h5>
                        <p class="card-text">Tax return for August.</p>
                        <a href="{{ route('journals.create') }}">
                            <button type="button" class="btn btn-secondary">New Entry</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="{{ asset('imgs/graphs.jpg') }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Cash</h5>
                        <p class="card-text">Outstanding Payments/Receipts : $580</p>
                        <button type="button" class="btn btn-secondary">New Transaction</button>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="{{ asset('imgs/graphs.jpg') }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Bank</h5>
                        <button type="button" class="btn btn-secondary">Online Synchronization</button>
                        <button type="button" class="btn btn-secondary">Create / Import Statements</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-frontend.layouts.master>

accMockup/resources/views/frontend/journals/journalEntries.blade.php
<x-frontend.layouts.master>
    <!-- <p>Date / Number / Partner / Reference / Journal / Total / Status</p>
    <p>d.m.y / MISC.no. / Blank / Blank / Type / Amount / Draft/Posted</p> -->



    <table class="table">
        <thead>
            <th scope="col">Journal</th>
            <th scope="col">Reference</th>
            <th scope="col">Date</th>
            <th scope="col">Status</th>
        </thead>
        <tbody>
            @foreach($journals as $journal)
            <tr>
            <td>{{ $journal->journalNo }}</td>
            <td>{{ $journal->reference }}</td>
            <td>{{ $journal->acc_date }}</td>
            <td>Drafted / Posted</td>
            </tr>
            @endforeach
        </tbody>
    </table>

</x-frontend.layouts.master>

accMockup/resources/views/frontend/journals/miscellaneousEntry.blade.php
<x-frontend.layouts.master>
    <h2>Miscellaneous Entry</h2>
    <div style="display: flex;">
        <button type="button" class="btn btn-primary" style="margin-right: 5px;">Save</button>
        <button type="button" class="btn btn-secondary" style="margin-right: 5px;">Discard</button>
        <button type="button" class="btn btn-warning" style="margin-right: 5px;">Post</button>
    </div>
    <div class="container">
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach 
        </ul>
    </div>
    @endif

        <form action="{{ route('journals.store') }}" method="post">
            @csrf
            <br>
            <br><br>
            <div class="row">
                <div class="col">
                    <label>Journal Number</label>
                    <input name="journalNo" type="text" class="form-control" placeholder="MISC/123456" value="{{ old('journalNo') }}">
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <label for="customer" class="form-label">Reference</label>
                    <input name="reference" type="text" class="form-control" aria-label="customer" value="{{ old('reference') }}">
                </div>
                <div class="col">
                    <label for="invoiceDate" class="form-label">Accounting Date</label>
                    <input name="acc_date" type="date" placeholder="dd-mm-yyyy" class="form-control" aria-label="invoiceDate" value="{{ old('acc_date') }}">
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col"></div>

                <div class="col">
                    <label for="dueDate" class="form-label">Journal</label>
                    <select class="form-select">
                        <option>Miscellaneous Operations</option>
                        <option>Exchange Difference</option>
                        <option>Cash Basis Taxes</option>
                    </select>
                </div>
            </div>
            <br>
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Invoice Lines</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Journal Items</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Other Info</button>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <table class="table">
                        <thead>
                            <th scope="col">Product</th>
                            <th scope="col">Label</th>
                            <th scope="col">Account</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Price</th>
                            <th scope="col">Taxes</th>
                            <th scope="col">SubTotal</th>
                        </thead>
                        <tbody>
                            <td>Add a Line</td>
                            <td>Add a Section</td>
                            <td>Add a Note</td>
                            <td>...</td>
                            <td>...</td>
                            <td>...</td>
                            <td>...</td>
                        </tbody>
                    </table>
                </div>

                <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    <table class="table">
                        <thead>
                            <th scope="col">Account</th>
                            <th scope="col">Label</th>
                            <th scope="col">Debit</th>
                            <th scope="col">Credit</th>
                            <th scope="col">Tax Grids</th>
                        </thead>
                        <tbody>
                            <td>Add a Line</td>
                            <td>...</td>
                            <td>...</td>
                            <td>...</td>
                            <td>...</td>
                        </tbody>
                    </table>
                </div>

                <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>


</x-frontend.layouts.master>

accMockup/resources/views/frontend/newBill.blade.php
<x-frontend.layouts.master>
    <h2>Vendor Bill Draft</h2>
    <div class="container">
        <br>
        <div style="display: flex; justify-content:space-around">
            <button type="button" class="btn btn-secondary">Preview</button>
            <button type="button" class="btn btn-secondary">Confirm</button>
        </div>
        <br><br>
        <div class="row">
            <div class="col">
                <label for="customer" class="form-label">Vendor</label>
                <input type="text" class="form-control" aria-label="customer">
            </div>
            <div class="col">
                <label for="invoiceDate" class="form-label">Bill Date</label>
                <input type="date" class="form-control" aria-label="invoiceDate">
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col">
                <label for="paymentReference" class="form-label">Bill Reference</label>
                <input type="text" class="form-control" aria-label="paymentReference">
            </div>
            <div class="col">
                <label for="dueDate" class="form-label">Accounting Date</label>
                <input type="date" class="form-control" aria-label="dueDate">
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col">
                <label for="paymentReference" class="form-label">Payment Reference</label>
                <input type="text" class="form-control" aria-label="paymentReference">
            </div>
            <div class="col">
                <label for="dueDate" class="form-label">Due Date</label>
                <input type="date" class="form-control" aria-label="dueDate">
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col">
                <label for="paymentReference" class="form-label">Recipient Bank</label>
                <input type="text" class="form-control" aria-label="paymentReference">
            </div>
            <div class="col">
                <label for="dueDate" class="form-label">Journal</label>
                <div class="row">
                    <div class="col-md-6">
                        <input type="text" class="form-control" aria-label="dueDate" placeholder="Vendor Bill">
                    </div>
                    <div class="col-md-1">
                        <label>in</label>
                    </div>
                    <div class="col-md-5">
                        <input type="text" class="form-control" aria-label="" placeholder="USD">
                    </div>
                </div>
            </div>
        </div>
        <br>
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Invoice Lines</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Journal Items</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Other Info</button>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                <table class="table">
                    <thead>
                        <th scope="col">Product</th>
                        <th scope="col">Label</th>
                        <th scope="col">Account</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Price</th>
                        <th scope="col">Taxes</th>
                        <th scope="col">SubTotal</th>
                    </thead>
                    <tbody>
                        <td>Add a Line</td>
                        <td>Add a Section</td>
                        <td>Add a Note</td>
                        <td>...</td>
                        <td>...</td>
                        <td>...</td>
                        <td>...</td>
                    </tbody>
                </table>
            </div>

            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                <table class="table">
                    <thead>
                        <th scope="col">Account</th>
                        <th scope="col">Label</th>
                        <th scope="col">Debit</th>
                        <th scope="col">Credit</th>
                        <th scope="col">Tax Grids</th>
                    </thead>
                    <tbody>
                        <td>Add a Line</td>
                        <td>...</td>
                        <td>...</td>
                        <td>...</td>
                        <td>...</td>
                    </tbody>
                </table>
            </div>

            <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
        </div>


</x-frontend.layouts.master>